/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 21 22:33:01 GMT 2019
 */

package main.java.view;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.LinkedList;
import java.util.List;
import main.java.view.Table;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Table_ESTest extends Table_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LinkedList<List<Object>> linkedList0 = new LinkedList<List<Object>>();
      LinkedList<String> linkedList1 = new LinkedList<String>();
      linkedList1.add("AtoZy@!EU\u0000a");
      Table<Object> table0 = new Table<Object>(linkedList0, linkedList1, linkedList1);
      linkedList1.add("");
      // Undeclared exception!
      try { 
        table0.toString();
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.LinkedList", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("2pgl\"#.dS$1So");
      linkedList0.offerFirst("2pgl\"#.dS$1So");
      LinkedList<List<String>> linkedList1 = new LinkedList<List<String>>();
      linkedList1.add((List<String>) linkedList0);
      linkedList1.add((List<String>) linkedList0);
      Table<String> table0 = new Table<String>(linkedList1, linkedList0, linkedList0);
      linkedList0.remove();
      linkedList0.add("+-----------------+-----------------------------+-----------------------------+\n|                 | 2pgl\"#.dS$1So             | 2pgl\"#.dS$1So             |\n+-----------------+-----------------------------+-----------------------------+\n| 2pgl\"#.dS$1So | java.lang.String@0000000003 | java.lang.String@0000000003 |\n+-----------------+-----------------------------+-----------------------------+\n| 2pgl\"#.dS$1So | java.lang.String@0000000003 | java.lang.String@0000000003 |\n+-----------------+-----------------------------+-----------------------------+\n");
      table0.toString();
      // Undeclared exception!
      table0.toString();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      Table<Object> table0 = new Table<Object>((List<List<Object>>) null, linkedList0, linkedList0);
      linkedList0.add("");
      // Undeclared exception!
      try { 
        table0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.java.view.Table", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      LinkedList<String> linkedList1 = new LinkedList<String>();
      linkedList1.add("\u001B[38m");
      Table<List<String>> table0 = new Table<List<String>>((List<List<List<String>>>) null, linkedList0, linkedList1);
      String string0 = table0.toString();
      assertEquals("+--+-------+\n|  | \u001B[38m |\n+--+-------+\n", string0);
  }
}
