/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 21 22:50:22 GMT 2019
 */

package main.java.view.viewmodel;

import org.junit.Test;
import static org.junit.Assert.*;
import main.java.view.viewmodel.RateOwnerCar;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RateOwnerCar_ESTest extends RateOwnerCar_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RateOwnerCar rateOwnerCar0 = new RateOwnerCar(0, 0);
      int int0 = rateOwnerCar0.getOwnerRate();
      assertEquals(0, int0);
      assertEquals(0, rateOwnerCar0.getCarRate());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RateOwnerCar rateOwnerCar0 = new RateOwnerCar(2184, 2184);
      int int0 = rateOwnerCar0.getOwnerRate();
      assertEquals(2184, rateOwnerCar0.getCarRate());
      assertEquals(2184, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RateOwnerCar rateOwnerCar0 = new RateOwnerCar((-550), 0);
      int int0 = rateOwnerCar0.getCarRate();
      assertEquals(0, int0);
      assertEquals((-550), rateOwnerCar0.getOwnerRate());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RateOwnerCar rateOwnerCar0 = new RateOwnerCar(2184, 2184);
      int int0 = rateOwnerCar0.getCarRate();
      assertEquals(2184, int0);
      assertEquals(2184, rateOwnerCar0.getOwnerRate());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RateOwnerCar rateOwnerCar0 = new RateOwnerCar((-3623), (-3623));
      int int0 = rateOwnerCar0.getCarRate();
      assertEquals((-3623), rateOwnerCar0.getOwnerRate());
      assertEquals((-3623), int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      RateOwnerCar rateOwnerCar0 = new RateOwnerCar((-3623), (-3623));
      int int0 = rateOwnerCar0.getOwnerRate();
      assertEquals((-3623), int0);
      assertEquals((-3623), rateOwnerCar0.getCarRate());
  }
}
