/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 10 16:39:29 GMT 2019
 */

package main.java.view.viewmodel;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import main.java.utils.Point;
import main.java.view.viewmodel.AutonomyCar;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AutonomyCar_ESTest extends AutonomyCar_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Point point0 = mock(Point.class, new ViolatedAssumptionAnswer());
      AutonomyCar autonomyCar0 = null;
      try {
        autonomyCar0 = new AutonomyCar(point0, 0, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.java.view.viewmodel.AutonomyCar", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AutonomyCar autonomyCar0 = null;
      try {
        autonomyCar0 = new AutonomyCar((Point) null, 2630, "|^~");
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.java.view.viewmodel.AutonomyCar", e);
      }
  }
}
