/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 10 19:12:26 GMT 2019
 */

package main.java;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.NoSuchElementException;
import main.java.Main;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Main_ESTest extends Main_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Main main0 = new Main();
      String[] stringArray0 = new String[6];
      stringArray0[0] = "z >r<X";
      SystemInUtil.addInputLine("z >r<X");
      stringArray0[1] = "lH#";
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile(".tmp");
      FileSystemHandling.shouldThrowIOException(evoSuiteFile0);
      stringArray0[2] = "\u001Bc";
      stringArray0[3] = "?`iQwUy/Sdpf&W$2 ";
      stringArray0[4] = "adasdsada1";
      stringArray0[5] = "nIW+B&)y=]N3U";
      Main.main(stringArray0);
      String[] stringArray1 = new String[2];
      stringArray1[1] = "";
      stringArray1[1] = "y";
      // Undeclared exception!
      try { 
        Main.main(stringArray1);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Main main0 = new Main();
      String[] stringArray0 = new String[7];
      stringArray0[0] = "";
      stringArray0[1] = "";
      stringArray0[2] = "";
      stringArray0[3] = "";
      stringArray0[4] = "adasdsada1";
      stringArray0[5] = "";
      stringArray0[6] = "]?5Q.6be00@H9";
      // Undeclared exception!
      try { 
        Main.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Main main0 = new Main();
      String[] stringArray0 = new String[6];
      stringArray0[0] = "z >r<X";
      SystemInUtil.addInputLine("z >r<X");
      stringArray0[1] = "lH#";
      stringArray0[2] = "\u001Bc";
      stringArray0[3] = "?`iQwUy/Sdpf&W$2 ";
      stringArray0[4] = "adasdsada1";
      stringArray0[5] = "nIW+B&)y=]N3U";
      Main.main(stringArray0);
      String[] stringArray1 = new String[2];
      stringArray1[1] = "";
      stringArray1[1] = "y";
      // Undeclared exception!
      try { 
        Main.main(stringArray1);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile(".tmp");
      FileSystemHandling.createFolder(evoSuiteFile0);
      Main main0 = new Main();
      String[] stringArray0 = new String[2];
      stringArray0[0] = "N?";
      stringArray0[1] = "8wonVg+V";
      // Undeclared exception!
      try { 
        Main.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }
}
