/*
 * This file was automatically generated by EvoSuite
 * Tue Dec 10 15:47:53 GMT 2019
 */

package main.java.model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import main.java.model.Car;
import main.java.model.CarModel;
import main.java.model.Client;
import main.java.model.Owner;
import main.java.model.Rental;
import main.java.utils.Point;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Car_ESTest extends Car_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Owner owner0 = new Owner("", "", "", 2919, "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.GAS;
      CarModel carModel0 = new CarModel(carModel_CarType0, 2919, "");
      Double double0 = new Double(2919);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("", owner0, carModel0, 0.0, 3538.8324, 2919, point0);
      car0.rate(2919);
      Client client0 = new Client(point0, "(sds", "", "(sds", "(sds", 4736);
      Rental rental0 = new Rental(car0, client0, point0);
      car0.pendingRental(rental0);
      Car car1 = car0.myclone();
      Rental rental1 = new Rental(car1, client0, point0);
      rental1.rate(0, 0);
      car1.approvePendingRental(rental1);
      assertEquals(0, owner0.getRates());
      assertFalse(car0.equals((Object)car1));
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      CarModel.CarType carModel_CarType0 = CarModel.CarType.GAS;
      CarModel carModel0 = new CarModel(carModel_CarType0, 0.0, "nI");
      Double double0 = new Double((-1235.592056813));
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("nI", (Owner) null, carModel0, 2678.25807, (-2074.968970573), 0, point0);
      Car car1 = car0.myclone();
      boolean boolean0 = car1.equals(car0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Owner owner0 = new Owner("", "", "", 2919, "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.GAS;
      CarModel carModel0 = new CarModel(carModel_CarType0, (-15.829658238083603), "");
      Double double0 = new Double((-15.829658238083603));
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("", owner0, carModel0, 0.0, 3538.8324, 2919, point0);
      Car car1 = car0.myclone();
      Double double1 = new Double((-146.39469667931));
      Point point1 = new Point(double1, double1);
      car1.setPosition(point1, (-1951.0));
      boolean boolean0 = car1.equals(car0);
      assertFalse(car1.equals((Object)car0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Owner owner0 = new Owner("\n", "", "z*~ U\"#`-6pvm5Akk,Y", 2978, "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.HYBRID;
      CarModel carModel0 = new CarModel(carModel_CarType0, 0.1, "");
      Double double0 = new Double(0L);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("z*~ U\"#`-6pvm5Akk,Y", owner0, carModel0, 2978, 0.1, 2978, point0);
      Car car1 = new Car("}=c=GP)+", owner0, carModel0, 2978, 0.1, 4125, point0);
      boolean boolean0 = car1.equals(car0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Owner owner0 = new Owner("", "", "", 2919, "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.HYBRID;
      CarModel carModel0 = new CarModel(carModel_CarType0, 0.0, "");
      Double double0 = new Double(0.0);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("", owner0, carModel0, 0.0, 3538.832375, 2919, point0);
      Car car1 = new Car("", owner0, carModel0, 0.0, 2919, 2919, point0);
      boolean boolean0 = car0.equals(car1);
      assertFalse(car1.equals((Object)car0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      CarModel.CarType carModel_CarType0 = CarModel.CarType.GAS;
      CarModel carModel0 = new CarModel(carModel_CarType0, 0.0, "nI");
      Double double0 = new Double((-1235.592056813));
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("nI", (Owner) null, carModel0, 2678.25807, (-2074.968970573), 0, point0);
      Car car1 = new Car("nI", (Owner) null, carModel0, 606.66487761869, (-1615.0), 0, point0);
      boolean boolean0 = car0.equals(car1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Owner owner0 = new Owner("", "", "", 446, "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.HYBRID;
      CarModel carModel0 = new CarModel(carModel_CarType0, 446, "");
      Double double0 = new Double(446);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("", owner0, carModel0, 446, 446, 446, point0);
      Client client0 = new Client(point0, "", "", "", "", 446);
      Rental rental0 = new Rental(car0, client0, point0);
      String string0 = rental0.toFinalString();
      assertEquals("Tempo Total: 0.00 Horas\nCusto Total: 0.00\n\n\u001B[4m\u001B[0m", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Owner owner0 = new Owner("urZsB/u@{E8J:`DGH", "urZsB/u@{E8J:`DGH", "urZsB/u@{E8J:`DGH", 417, "b");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.GAS;
      CarModel carModel0 = new CarModel(carModel_CarType0, 417, "b");
      Double double0 = new Double(3);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("urZsB/u@{E8J:`DGH", owner0, carModel0, 417, 0.0, 3, point0);
      car0.rate(0, 2173);
      assertEquals(2173, owner0.getRates());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CarModel.CarType carModel_CarType0 = CarModel.CarType.GAS;
      CarModel carModel0 = new CarModel(carModel_CarType0, 0.0, "nI");
      Double double0 = new Double((-1235.592056813));
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("nI", (Owner) null, carModel0, 2678.25807, 1201.0, 0, point0);
      boolean boolean0 = car0.hasRange(point0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Owner owner0 = new Owner("&J<S4S]r/c}[dG", ",pBxigV8", ",pBxigV8", 0, (String) null);
      Double double0 = new Double(0);
      Double double1 = new Double(1.2);
      Point point0 = new Point(double0, double1);
      Car car0 = new Car("&J<S4S]r/c}[dG", owner0, (CarModel) null, 0, 0, 0, point0);
      Point point1 = new Point(double1, double1);
      boolean boolean0 = car0.hasRange(point1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Owner owner0 = new Owner("", (String) null, "%.2f Horas", (-1516), "O carro necessita de ser abastecido\n");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ELECTRIC;
      CarModel carModel0 = new CarModel(carModel_CarType0, 0.0, "O carro necessita de ser abastecido\n");
      Double double0 = new Double((-1516));
      Point point0 = new Point(double0, double0);
      Car car0 = new Car((String) null, owner0, carModel0, (-1516), 1165.7143407778287, 1339, point0);
      car0.rate(0);
      car0.rate(1339);
      Car car1 = car0.myclone();
      assertEquals(CarModel.CarType.ELECTRIC, car1.getType());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Owner owner0 = new Owner("", "", "", 2919, "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ELECTRIC;
      CarModel carModel0 = new CarModel(carModel_CarType0, 0.0, "");
      Double double0 = new Double(0.0);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("", owner0, carModel0, 0.0, 3538.832375, 2919, point0);
      boolean boolean0 = car0.isAvailable();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Owner owner0 = new Owner("", "", "/iB=dHc_F`", 0, (String) null);
      CarModel carModel0 = new CarModel((CarModel.CarType) null, 0, (String) null);
      Car car0 = new Car("", owner0, carModel0, 68.95900783, (-180.324669), 0, (Point) null);
      car0.getType();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Owner owner0 = new Owner("", "<`t;", "", 610, "ree\"[FcvHU3-IQJL");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.HYBRID;
      CarModel carModel0 = new CarModel(carModel_CarType0, 610, "dI740x`/fN?Yd1zj@");
      Double double0 = new Double(1908.0);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("ree\"[FcvHU3-IQJL", owner0, carModel0, 1908.0, 610, 610, point0);
      CarModel.CarType carModel_CarType1 = car0.getType();
      assertEquals(CarModel.CarType.HYBRID, carModel_CarType1);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Owner owner0 = new Owner("", "", "", 0, "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ANY;
      CarModel carModel0 = new CarModel(carModel_CarType0, (-3452.6643378504077), "_y-Ef|");
      Double double0 = new Double((-3452.6643378504077));
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("", owner0, carModel0, (-3452.6643378504077), (-2761.0), 0, point0);
      double double1 = car0.getRange();
      assertEquals(0.0, double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Owner owner0 = new Owner("", "<`t;", "", 610, "ree\"[FcvHU3-IQJL");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.HYBRID;
      CarModel carModel0 = new CarModel(carModel_CarType0, 610, "dI740x`/fN?Yd1zj@");
      Double double0 = new Double(1908.0);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("ree\"[FcvHU3-IQJL", owner0, carModel0, 1908.0, 610, 610, point0);
      double double1 = car0.getRange();
      assertEquals(610.0, double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Owner owner0 = new Owner((String) null, (String) null, "", 429, "Tempo a p\u00E9      ");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ELECTRIC;
      CarModel carModel0 = new CarModel(carModel_CarType0, 429, "|UK]~V#Y :8ATNdhf4[");
      Car car0 = new Car("Tempo Estimado: ", owner0, carModel0, (-1.0), (-1.0), (-2469), (Point) null);
      double double0 = car0.getRange();
      assertEquals((-2469.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Owner owner0 = new Owner("x`:N(", "r", "x`:N(", (-2560), "x`:N(");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.HYBRID;
      CarModel carModel0 = new CarModel(carModel_CarType0, (-2560), "r");
      Car car0 = new Car("x`:N(", owner0, carModel0, 1368.86945, (-2760.5987037654654), (-2560), (Point) null);
      Point point0 = car0.getPosition();
      assertNull(point0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Owner owner0 = new Owner((String) null, (String) null, "J0Zb]ldHK>b+YK", 0, "J0Zb]ldHK>b+YK");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ELECTRIC;
      CarModel carModel0 = new CarModel(carModel_CarType0, 0, "Tempo a p\u00E9      ");
      Double double0 = new Double(0.0);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car((String) null, owner0, carModel0, 0.0, 0, 0, point0);
      Point point1 = car0.getPosition();
      assertSame(point0, point1);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Owner owner0 = new Owner("", "", "", 1473122002, "yyyy-MM-dd HH:mm");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ANY;
      CarModel carModel0 = new CarModel(carModel_CarType0, 1473122002, "");
      Double double0 = new Double(2600.7549577758);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car((String) null, owner0, carModel0, 1473122002, 2600.7549577758, (-768), point0);
      Point point1 = car0.getPosition();
      assertEquals(2600.7549577758, point1.getX(), 0.01);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Owner owner0 = new Owner("", (String) null, "%.2f Horas", (-1516), "O carro necessita de ser abastecido\n");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ELECTRIC;
      CarModel carModel0 = new CarModel(carModel_CarType0, 0.0, "O carro necessita de ser abastecido\n");
      Double double0 = new Double((-1516));
      Point point0 = new Point(double0, double0);
      Car car0 = new Car((String) null, owner0, carModel0, (-1516), 1165.7143407778287, 1339, point0);
      Point point1 = car0.getPosition();
      assertSame(point0, point1);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Owner owner0 = new Owner((String) null, "", "+", 0, ".| ]{[hz|_y~\"");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.HYBRID;
      CarModel carModel0 = new CarModel(carModel_CarType0, 0, "\n");
      Double double0 = new Double(0.0);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car(".| ]{[hz|_y~\"", owner0, carModel0, 0, 0, 0, point0);
      String string0 = car0.getOwnerID();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Owner owner0 = new Owner("main.java.model.Client", "", "\"\"_rs'K", 1831, "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ANY;
      CarModel carModel0 = new CarModel(carModel_CarType0, 1831, "main.java.model.Client");
      Double double0 = new Double(1831);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("main.java.model.Client", owner0, carModel0, 1831, 1831, 1831, point0);
      String string0 = car0.getOwnerID();
      assertEquals("main.java.model.Client", string0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Owner owner0 = new Owner("", "", "", 0, "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ANY;
      CarModel carModel0 = new CarModel(carModel_CarType0, (-3452.6643378504077), "_y-Ef|");
      Double double0 = new Double((-3452.6643378504077));
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("", owner0, carModel0, (-3452.6643378504077), (-2761.0), 0, point0);
      String string0 = car0.getOwnerID();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Owner owner0 = new Owner((String) null, (String) null, (String) null, 0, "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.GAS;
      CarModel carModel0 = new CarModel(carModel_CarType0, 0.2, "");
      Double double0 = new Double(1225.39291);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car((String) null, owner0, carModel0, 0, 0, 0, point0);
      String string0 = car0.getNumberPlate();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ANY;
      CarModel carModel0 = new CarModel(carModel_CarType0, (-3346.624), "L\"dMJ>XWGA?jR\"");
      Car car0 = new Car(" fS3r)Nu#8", (Owner) null, carModel0, (-3346.624), (-3346.624), 0, (Point) null);
      String string0 = car0.getNumberPlate();
      assertEquals(" fS3r)Nu#8", string0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Owner owner0 = new Owner("", "", "", 2919, "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ELECTRIC;
      CarModel carModel0 = new CarModel(carModel_CarType0, 2919, "");
      Double double0 = new Double(2919);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("", owner0, carModel0, 2919, 2919, 2919, point0);
      String string0 = car0.getNumberPlate();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Owner owner0 = new Owner("", "", "", 376, "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ANY;
      CarModel carModel0 = new CarModel(carModel_CarType0, 376, "E$");
      Double double0 = new Double(0.0);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("", owner0, carModel0, 494.288507, 494.288507, 376, point0);
      car0.setBasePrice(0.0);
      double double1 = car0.getBasePrice();
      assertEquals(0.0, double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Owner owner0 = new Owner("", "", "", 1473122002, "yyyy-MM-dd HH:mm");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ANY;
      CarModel carModel0 = new CarModel(carModel_CarType0, 1473122002, "");
      Double double0 = new Double(2600.7549577758);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car((String) null, owner0, carModel0, 1473122002, 2600.7549577758, (-768), point0);
      double double1 = car0.getBasePrice();
      assertEquals(1.473122002E9, double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Owner owner0 = new Owner("%.2f", "main.java.model.Rental", "\n", (-1403), "main.java.model.Car");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.HYBRID;
      CarModel carModel0 = new CarModel(carModel_CarType0, 0.5, "%.2f");
      Double double0 = new Double((-3104.0));
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("\n", owner0, carModel0, (-3104.0), 0.4, (-1403), point0);
      double double1 = car0.getBasePrice();
      assertEquals((-3104.0), double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Owner owner0 = new Owner("", "", "/iB=dHc_F`", 0, (String) null);
      CarModel.CarType carModel_CarType0 = CarModel.CarType.GAS;
      CarModel carModel0 = new CarModel(carModel_CarType0, 0, "yyyy-MM-dd HH:mm");
      Car car0 = new Car("", owner0, carModel0, 68.95900783, (-180.324669), 0, (Point) null);
      double double0 = car0.getAvgSpeed();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Owner owner0 = new Owner("urZsB/u@{E8J:`DGH", "urZsB/u@{E8J:`DGH", "urZsB/u@{E8J:`DGH", 417, "b");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.GAS;
      CarModel carModel0 = new CarModel(carModel_CarType0, 417, "b");
      Double double0 = new Double(3);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("urZsB/u@{E8J:`DGH", owner0, carModel0, 417, 0.0, 3, point0);
      double double1 = car0.getAvgSpeed();
      assertEquals(417.0, double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Owner owner0 = new Owner("a!`E4$h;bFY", "O carro necessita de ser abastecido\n", "_C2iEnG!{ZtL2Amd9C", (-393), "!qP#pITfOi*^)4r-");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.HYBRID;
      CarModel carModel0 = new CarModel(carModel_CarType0, (-393), "");
      Double double0 = new Double((-393));
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("O carro necessita de ser abastecido\n", owner0, carModel0, 0.0, 0.0, (-393), point0);
      double double1 = car0.getAvgSpeed();
      assertEquals((-393.0), double1, 0.01);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Owner owner0 = new Owner("", "", "", (-2727), "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.GAS;
      CarModel carModel0 = new CarModel(carModel_CarType0, (-2727), ")\"E%k{<?'");
      Car car0 = new Car("", owner0, carModel0, (-2727), (-2727), (-2727), (Point) null);
      // Undeclared exception!
      try { 
        car0.setPosition((Point) null, 0.0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.java.model.Car", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      CarModel.CarType carModel_CarType0 = CarModel.CarType.GAS;
      CarModel carModel0 = new CarModel(carModel_CarType0, 1892.9178482340049, "");
      Double double0 = new Double(5841.294291);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("", (Owner) null, carModel0, (-3108.91770343043), 749.121950766, 3, point0);
      // Undeclared exception!
      try { 
        car0.rate(3, 3);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.java.model.Car", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      CarModel.CarType carModel_CarType0 = CarModel.CarType.GAS;
      CarModel carModel0 = new CarModel(carModel_CarType0, 0.0, "G@N]_}&kN'G=");
      Double double0 = new Double(2758.3);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("G@N]_}&kN'G=", (Owner) null, carModel0, 2758.3, 0.0, 320, point0);
      Client client0 = new Client(point0, "\n", "", "main.java.model.CarModel$CarType", "gvf+d4^*P8O!ws.6[6<", 0);
      Rental rental0 = new Rental(car0, client0, point0);
      // Undeclared exception!
      try { 
        car0.pendingRental(rental0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.java.model.Car", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Owner owner0 = new Owner("", "HNn-BV]6b}sq};ku[L%", "", (-1401), "");
      Car car0 = new Car("\"_w#]jd=KUPtbli8g#", owner0, (CarModel) null, 3554.11609, (-1831.618580262245), 2600, (Point) null);
      // Undeclared exception!
      try { 
        car0.myclone();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      CarModel.CarType carModel_CarType0 = CarModel.CarType.GAS;
      CarModel carModel0 = new CarModel(carModel_CarType0, (-151.65), "Rsl|8G<k(0(&");
      Double double0 = new Double(0);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("Rsl|8G<k(0(&", (Owner) null, carModel0, (-151.65), 0.0, 0, point0);
      // Undeclared exception!
      try { 
        car0.getOwnerID();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.java.model.Car", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Owner owner0 = new Owner("", "\n", "", 0, "");
      Double double0 = new Double((-1.0));
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("", owner0, (CarModel) null, 0, 2.0, 0, point0);
      // Undeclared exception!
      try { 
        car0.getAvgSpeed();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.java.model.Car", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Owner owner0 = new Owner("", "", "", 2919, "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.GAS;
      CarModel carModel0 = new CarModel(carModel_CarType0, 2919, "");
      Double double0 = new Double(2919);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("", owner0, carModel0, 2919, 2919, 2919, point0);
      car0.rate(2919);
      Car car1 = car0.myclone();
      Client client0 = new Client(point0, ")", "O carro necessita de ser abastecido\n", ")", ")", 2919);
      Rental rental0 = new Rental(car0, client0, point0);
      car0.approvePendingRental(rental0);
      Rental rental1 = new Rental(car1, client0, point0);
      car1.approvePendingRental(rental1);
      // Undeclared exception!
      try { 
        car0.equals(car1);
        fail("Expecting exception: StackOverflowError");
      
      } catch(StackOverflowError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      CarModel.CarType carModel_CarType0 = CarModel.CarType.GAS;
      CarModel carModel0 = new CarModel(carModel_CarType0, 0.0, "nI");
      Double double0 = new Double((-1235.592056813));
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("nI", (Owner) null, carModel0, 2678.25807, (-2074.968970573), 0, point0);
      Car car1 = car0.myclone();
      Car car2 = car1.myclone();
      // Undeclared exception!
      try { 
        car1.equals(car2);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      CarModel.CarType carModel_CarType0 = CarModel.CarType.GAS;
      CarModel carModel0 = new CarModel(carModel_CarType0, 239.966, "DQAM");
      Double double0 = new Double((-1677.40828060892));
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("DQAM", (Owner) null, carModel0, 239.966, (-661.5), 1886, point0);
      Rental rental0 = new Rental(car0, (Client) null, point0);
      // Undeclared exception!
      try { 
        car0.approvePendingRental(rental0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.java.model.Car", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Owner owner0 = new Owner("SiPh,^kF6", "SiPh,^kF6", (String) null, 804, "SiPh,^kF6");
      Double double0 = new Double(804);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("SiPh,^kF6", owner0, (CarModel) null, 0L, 0L, 0, point0);
      // Undeclared exception!
      try { 
        car0.getType();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Owner owner0 = new Owner("", "", "", 2919, "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ELECTRIC;
      CarModel carModel0 = new CarModel(carModel_CarType0, 2919, "");
      Double double0 = new Double(2919);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("", owner0, carModel0, 2919, 2919, 2919, point0);
      car0.rate(2919);
      Car car1 = car0.myclone();
      Client client0 = new Client(point0, "", "", "", "", 2919);
      Rental rental0 = new Rental(car1, client0, point0);
      assertTrue(car0.equals((Object)car1));
      
      car1.approvePendingRental(rental0);
      boolean boolean0 = car0.equals(car1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Owner owner0 = new Owner("I", "J", "J", 2969, "J");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.HYBRID;
      CarModel carModel0 = new CarModel(carModel_CarType0, 2969, "I");
      Double double0 = new Double((-1L));
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("J", owner0, carModel0, 2969, (-1L), 2969, point0);
      Car car1 = new Car("I", owner0, carModel0, 2969, (-1L), 2969, point0);
      boolean boolean0 = car0.equals(car1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Owner owner0 = new Owner("", "", "", 2919, "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.GAS;
      CarModel carModel0 = new CarModel(carModel_CarType0, 2919, "");
      Double double0 = new Double(2919);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("", owner0, carModel0, 2919, 2919, 2919, point0);
      car0.rate(2919);
      Car car1 = car0.myclone();
      Client client0 = new Client(point0, "", "", "", "", 2919);
      Rental rental0 = new Rental(car1, client0, point0);
      rental0.rate(0, 0);
      boolean boolean0 = car0.equals(car1);
      assertEquals(0, owner0.getRates());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Owner owner0 = new Owner("", "", "", 2919, "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ELECTRIC;
      CarModel carModel0 = new CarModel(carModel_CarType0, 2919, "");
      Double double0 = new Double(2919);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("", owner0, carModel0, 2919, 2919, 2919, point0);
      car0.rate(2919);
      Car car1 = car0.myclone();
      boolean boolean0 = car0.equals(car1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Owner owner0 = new Owner("&}LjR>u)@kye*%D", "&}LjR>u)@kye*%D", "&}LjR>u)@kye*%D", 2919, "&}LjR>u)@kye*%D");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ANY;
      CarModel carModel0 = new CarModel(carModel_CarType0, (-15.829658238083603), "&}LjR>u)@kye*%D");
      Double double0 = new Double((-15.829658238083603));
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("&}LjR>u)@kye*%D", owner0, carModel0, 2919, (-15.829658238083603), 2919, point0);
      Car car1 = car0.myclone();
      Double double1 = new Double(2919);
      Point point1 = new Point(double1, double1);
      car1.setPosition(point1, (-15.829658238083603));
      boolean boolean0 = car0.equals(car1);
      assertFalse(car1.equals((Object)car0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Owner owner0 = new Owner("", "", "", 2919, "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ELECTRIC;
      CarModel carModel0 = new CarModel(carModel_CarType0, 0.0, "");
      Double double0 = new Double(0.0);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("", owner0, carModel0, 0.0, 3538.832375, 2919, point0);
      Car car1 = car0.myclone();
      car1.swapState();
      boolean boolean0 = car0.equals(car1);
      assertFalse(car1.equals((Object)car0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Owner owner0 = new Owner("GAS", "GAS", "GAS", 2978, "GAS");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.GAS;
      CarModel carModel0 = new CarModel(carModel_CarType0, 19L, "GAS");
      Double double0 = new Double(19L);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("GAS", owner0, carModel0, 2978, 19L, 2978, point0);
      Car car1 = new Car("GAS", owner0, carModel0, 2978, 19L, 4153, point0);
      boolean boolean0 = car0.equals(car1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Owner owner0 = new Owner("%.2f", "%.2f", "%.2f", 2919, "%.2f");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.HYBRID;
      CarModel carModel0 = new CarModel(carModel_CarType0, (-18.44077101181202), "%.2f");
      Double double0 = new Double((-18.44077101181202));
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("%.2f", owner0, carModel0, (-18.44077101181202), (-18.44077101181202), 2919, point0);
      Car car1 = new Car("%.2f", owner0, carModel0, (-18.44077101181202), 2919, 2919, point0);
      boolean boolean0 = car0.equals(car1);
      assertFalse(boolean0);
      assertFalse(car1.equals((Object)car0));
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ELECTRIC;
      CarModel carModel0 = new CarModel(carModel_CarType0, 624.2878159127713, " Ih/4(($HdF");
      Double double0 = new Double((-471L));
      Point point0 = new Point(double0, double0);
      Car car0 = new Car(" Ih/4(($HdF", (Owner) null, carModel0, (-471L), (-471L), (-29), point0);
      Car car1 = new Car(" Ih/4(($HdF", (Owner) null, carModel0, 624.2878159127713, (-29), (-29), point0);
      boolean boolean0 = car0.equals(car1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Owner owner0 = new Owner("", "", "", 1473122002, "yyyy-MM-dd HH:mm");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ANY;
      CarModel carModel0 = new CarModel(carModel_CarType0, 1473122002, "");
      Double double0 = new Double(2600.7549577758);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car((String) null, owner0, carModel0, 1473122002, 2600.7549577758, (-768), point0);
      CarModel carModel1 = new CarModel(carModel_CarType0, 0.0, "%.2f");
      Car car1 = new Car("", owner0, carModel1, (-2132.4), (-527.70180311916), 1473122002, point0);
      boolean boolean0 = car0.equals(car1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Owner owner0 = new Owner("", "", "", 2919, "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ELECTRIC;
      CarModel carModel0 = new CarModel(carModel_CarType0, 2919, "");
      Double double0 = new Double(2919);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("", owner0, carModel0, 2919, 2919, 2919, point0);
      Car car1 = car0.myclone();
      boolean boolean0 = car0.equals(car1);
      assertFalse(car1.equals((Object)car0));
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Owner owner0 = new Owner((String) null, "K[x87(>HhyGy", "K[x87(>HhyGy", 0, "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.HYBRID;
      CarModel carModel0 = new CarModel(carModel_CarType0, 0.2, "O carro necessita de ser abastecido\n");
      Double double0 = new Double(0.2);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car((String) null, owner0, carModel0, 0.0, 0.2, 0, point0);
      boolean boolean0 = car0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Owner owner0 = new Owner("", "", "", 2919, "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.GAS;
      CarModel carModel0 = new CarModel(carModel_CarType0, 2919, "");
      Double double0 = new Double(2919);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("", owner0, carModel0, 2919, 2919, 2919, point0);
      boolean boolean0 = car0.equals(car0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      CarModel.CarType carModel_CarType0 = CarModel.CarType.HYBRID;
      CarModel carModel0 = new CarModel(carModel_CarType0, (-371.4696477), "%.2f");
      Double double0 = new Double((-371.4696477));
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("cV", (Owner) null, carModel0, (-371.4696477), (-371.4696477), 0, point0);
      boolean boolean0 = car0.equals("cV");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      CarModel.CarType carModel_CarType0 = CarModel.CarType.HYBRID;
      CarModel carModel0 = new CarModel(carModel_CarType0, (-371.4696477), "%.2f");
      Double double0 = new Double((-371.4696477));
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("cV", (Owner) null, carModel0, (-371.4696477), (-371.4696477), 0, point0);
      Double double1 = new Double(0.1);
      Point point1 = new Point(double1, double0);
      car0.setPosition(point1, 0);
      String string0 = car0.warnings();
      assertEquals("O carro necessita de ser abastecido\n", string0);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      Owner owner0 = new Owner("", "", "/iB=dHc_F`", 0, (String) null);
      CarModel.CarType carModel_CarType0 = CarModel.CarType.GAS;
      CarModel carModel0 = new CarModel(carModel_CarType0, 0, "yyyy-MM-dd HH:mm");
      Car car0 = new Car("", owner0, carModel0, 68.95900783, (-180.324669), 0, (Point) null);
      String string0 = car0.warnings();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      Owner owner0 = new Owner("", "", "", 2919, "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ELECTRIC;
      CarModel carModel0 = new CarModel(carModel_CarType0, 2919, "");
      Double double0 = new Double(2919);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("", owner0, carModel0, 2919, 2919, 2919, point0);
      boolean boolean0 = car0.hasRange(point0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      CarModel.CarType carModel_CarType0 = CarModel.CarType.HYBRID;
      CarModel carModel0 = new CarModel(carModel_CarType0, (-371.4696477), "%.2f");
      Double double0 = new Double((-371.4696477));
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("cV", (Owner) null, carModel0, (-371.4696477), (-371.4696477), 0, point0);
      Double double1 = new Double(0.1);
      Point point1 = new Point(double1, double0);
      car0.setPosition(point1, 0);
      boolean boolean0 = car0.hasRange(point0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      Owner owner0 = new Owner("", "", "/iB=dHc_F`", 0, (String) null);
      CarModel.CarType carModel_CarType0 = CarModel.CarType.GAS;
      CarModel carModel0 = new CarModel(carModel_CarType0, 0, "yyyy-MM-dd HH:mm");
      Car car0 = new Car("", owner0, carModel0, 68.95900783, (-180.324669), 0, (Point) null);
      // Undeclared exception!
      try { 
        car0.hasRange((Point) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.java.model.Car", e);
      }
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      Owner owner0 = new Owner("", "", "", 2919, "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ELECTRIC;
      CarModel carModel0 = new CarModel(carModel_CarType0, 2919, "");
      Double double0 = new Double(2919);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("", owner0, carModel0, 2919, 2919, 2919, point0);
      car0.swapState();
      car0.swapState();
      assertEquals(CarModel.CarType.ELECTRIC, car0.getType());
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      Owner owner0 = new Owner("", "", "", 2919, "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ELECTRIC;
      CarModel carModel0 = new CarModel(carModel_CarType0, 0.0, "");
      Double double0 = new Double(0.0);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("", owner0, carModel0, 0.0, 3538.832375, 2919, point0);
      car0.swapState();
      boolean boolean0 = car0.isAvailable();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      Owner owner0 = new Owner("", "", "", 2919, "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ELECTRIC;
      CarModel carModel0 = new CarModel(carModel_CarType0, 0.0, "");
      Double double0 = new Double(0.0);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("", owner0, carModel0, 0.0, 3538.832375, 2919, point0);
      car0.hashCode();
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      Owner owner0 = new Owner("", "", "", 2919, "");
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ELECTRIC;
      CarModel carModel0 = new CarModel(carModel_CarType0, 0.0, "");
      Double double0 = new Double(0.0);
      Point point0 = new Point(double0, double0);
      Car car0 = new Car("", owner0, carModel0, 0.0, 3538.832375, 2919, point0);
      car0.refil();
      assertEquals(CarModel.CarType.ELECTRIC, car0.getType());
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      CarModel.CarType carModel_CarType0 = CarModel.CarType.ELECTRIC;
      CarModel carModel0 = new CarModel(carModel_CarType0, 624.2878159127713, " Ih/4(($HdF");
      Double double0 = new Double((-471L));
      Point point0 = new Point(double0, double0);
      Car car0 = new Car(" Ih/4(($HdF", (Owner) null, carModel0, (-471L), (-471L), (-29), point0);
      String string0 = car0.toString();
      assertEquals(" Ih/4(($HdF\n-29.00\n-471.00\ntrue\n100", string0);
  }
}
