/*
 * This file was automatically generated by EvoSuite
 * Thu Nov 21 22:44:57 GMT 2019
 */

package main.java.model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import main.java.model.Traffic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.System;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Traffic_ESTest extends Traffic_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Traffic traffic0 = new Traffic();
      double double0 = traffic0.getTraficDelay((-76.0825736767804));
      assertEquals((-0.08257367678039462), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Traffic traffic0 = new Traffic();
      traffic0.b = null;
      // Undeclared exception!
      try { 
        traffic0.getTraficDelay(0.0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("main.java.model.Traffic", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      System.setCurrentTimeMillis(120L);
      Traffic traffic0 = new Traffic();
      double double0 = traffic0.getTraficDelay(120L);
      assertEquals(0.19999999999999335, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Traffic traffic0 = new Traffic();
      traffic0.getTraficDelay(0.0);
      double double0 = traffic0.getTraficDelay(622.293059712);
      assertEquals(0.1930597119999102, double0, 0.01);
  }
}
